version: "3"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer
      - mongodb
    env_file:
      - .env
    networks:
      - my_network

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    container_name: presidio-analyzer
    ports:
      - "5001:3000"
    networks:
      - my_network

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    ports:
      - "5002:3000"
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

volumes:
  mongodb_data:

networks:
  my_network:
